Repository cowprotocol/docs, pull requests merged in 2023-10, with the labels that each got.

#11 chore: config and layout
  docs/README.md
  docs/cow-protocol/analyse/README.mdx
  docs/cow-protocol/analyse/dune.md
  docs/cow-protocol/analyse/subgraph.md
  docs/cow-protocol/arbitrate/README.mdx
  docs/cow-protocol/arbitrate/autopilot.md
  docs/cow-protocol/arbitrate/driver.md
  docs/cow-protocol/create/cowswap-ui/README.mdx
  docs/cow-protocol/create/cowswap-ui/_category_.json
  docs/cow-protocol/create/cowswap-ui/cancel.md
  docs/cow-protocol/create/cowswap-ui/limit.md
  docs/cow-protocol/create/cowswap-ui/native.md
  docs/cow-protocol/create/cowswap-ui/swap.md
  docs/cow-protocol/create/cowswap-ui/twap.md
  docs/cow-protocol/create/custom-integration/README.mdx
  docs/cow-protocol/create/custom-integration/_category_.json
  docs/cow-protocol/create/custom-integration/hook.md
  docs/cow-protocol/create/custom-integration/script.md
  docs/cow-protocol/create/custom-integration/widget.md
  docs/cow-protocol/create/protocol-integration/README.mdx
  docs/cow-protocol/create/protocol-integration/_category_.json
  docs/cow-protocol/create/protocol-integration/liquidation.md
  docs/cow-protocol/message/README.mdx
  docs/cow-protocol/reference/apis/orderbook.mdx
  docs/cow-protocol/reference/apis/solver.mdx
  docs/cow-protocol/settle/README.mdx
  docs/cow-protocol/settle/contracts.md
  docs/cow-protocol/solve/README.mdx
  docs/cow-protocol/solve/create.md
  docs/cow-protocol/solve/deploy.md
  docs/cow-protocol/view/explorer/README.mdx
  docs/cow-protocol/view/explorer/_category_.json
  docs/cow-protocol/view/explorer/batch_auction.md
  docs/cow-protocol/view/explorer/user.md
  docs/cow-sdk/order-meta-data-appdata/create-a-meta-data-document.md
  docs/front-end/creating-app-ids/upload-the-file-to-ipfs.md
  docs/overview/cow-hooks/cow-hooks-example/permit-swap-and-bridge-cow-hook.md
  docs/solvers/in-depth-solver-specification/output-batch-auction-solutions.md
  docs/solvers/in-depth-solver-specification/the-batch-auction-optimization-problem.md
  docs/tutorials/cowswap-trades-with-a-gnosis-safe-wallet/conclusion.md
  docusaurus.config.ts
  package.json
  sidebars.js
  sidebars.ts
  src/components/HomepageFeatures/index.tsx
  src/components/swagger-doc/SwaggerDoc.tsx
  src/components/swagger-doc/swagger-ui.css
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: E:2.1: Documentation and Tutorials

#12 feat: update theme
  docusaurus.config.ts
  src/css/custom.css
  static/img/cow-logo-dark.svg
  static/img/cow-logo.svg
  static/img/favicon.ico
  static/img/favicon.png
  static/img/og-meta-cowprotocol.png
Labels: E:2.1: Documentation and Tutorials

#14 doc: delete unecesary $
  README.md
Labels: bug

#21 chore: repo config
  docusaurus.config.js
  package.json
  sidebars.js
  tsconfig.json
  yarn.lock
Labels: infra, E:2.1: Documentation and Tutorials

#22 fix: components
  docs/README.md
  package.json
  src/components/HomepageFeatures/index.tsx
  yarn.lock
Labels: bug
